### ISSUE TITLE
Radare2 (v2.6.0) dotfile compatibility

### ISSUE THREAD

**Issue by sferrini** [Siguza/Stash#1]
According to https://github.com/radare/radare2/pull/10085, in the r2 codebase they refactored the `asm.lineswidth` evar to `asm.lines.width` so if/when you upgrade your r2 version you may have to upgrade this line https://github.com/Siguza/Stash/blob/master/dotfiles/radare2.rc#L1 ;)

**Comment by Siguza** [comment]
Wow, you're keeping track better than me. O_O

**Comment by Siguza** [comment]
Fixed in cf522dd68af940ed6b3163702c3b9c0118e93445. :)
